Add option cookie
novaway/tarte-a-la-praline pull request #11
Opened 2020-12-11 12:38 UTC by marcbalme

2020-12-11 14:22 UTC, stephane-r commented on src/utils/camelCase.ts
> +export default camelCase;
Tu utilises toute les fonctions qui sont présente dans ce fichier ?

2020-12-11 14:22 UTC, stephane-r commented on src/index.ts
> +        description: "lorem uihhufhsu uihfues "
A voir pour mettre peut-être de meilleur fixtures ^^

2020-12-11 14:22 UTC, stephane-r commented
Visuellement, il faudrait affiner l'UI en augmentant un peu le margin-bottom du container du label d'un service et aligné la description avec le label. En état, visuellement c'est pas tip-top ^^

![image](https://user-images.githubusercontent.com/4712791/101913609-7dca3f00-3bc3-11eb-84dc-ad65a901a832.png)

2020-12-11 14:24 UTC, stephane-r requested changes

2020-12-11 14:24 UTC, stephane-r commented on src/templates/CustomSelection/index.ts
> +                  ${description !== undefined ? `${description}` : ""}
C'est dommage la description n'est pas cliquable. Rajoute la dans ton `label` et comme ça tu auras 2 avantages : 

- tout le service sera "checkable"
- la description sera aligné avec ton label :)

2020-12-11 14:48 UTC, marcbalme commented on src/utils/camelCase.ts
> +export default camelCase;
oui elles sont toutes appelé dans la fonction camelCase

2020-12-14 08:21 UTC, stephane-r commented on src/utils/storage.ts
> +  console.log(services, "storage.ts");
Tu peux le supprimer

2020-12-14 09:37 UTC, stephane-r commented
C'est good pour moi :)

2020-12-14 09:40 UTC, merged